apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.FqdnSafe }}"
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.FqdnSafe }}"
  targetCPUUtilizationPercentage: 50
